"""Behavior contracts for shared backport implementations."""

from __future__ import annotations

import logging
import subprocess
from types import SimpleNamespace
from unittest.mock import Mock

import pytest

from scripts.backport import cherry_pick as cherry_pick_module
from scripts.backport import (
    conflict_resolver,
    git,
    main,
    mark_done,
    pr_creator,
    sweep,
    sweep_apply,
    sweep_prs,
    sweep_validation,
)
from scripts.backport.models import BackportPRContext
from scripts.backport.pr_creator import BackportPRCreator, find_pull_by_head
from scripts.backport.project_graphql import load_project_v2
from scripts.backport.registry import ValidationRule
from scripts.backport.sweep_models import BranchSweepResult, CandidateResult
from scripts.backport.sweep_reporting import build_pr_body as build_sweep_pr_body
from scripts.backport.validation import validate_branch
from scripts.common.identity import BOT_EMAIL, BOT_NAME


def test_pr_body_formats_remain_stable_after_renderer_unification() -> None:
    context = BackportPRContext(
        source_pr_number=42,
        source_pr_title="Fix | parser\nhandling",
        source_pr_url="https://github.com/o/r/pull/42",
        source_pr_diff="",
        target_branch="8.1",
        commits=["abc"],
    )
    per_pr_body = BackportPRCreator.build_pr_body(
        context,
        had_conflicts=False,
        resolution_results=None,
        applied_commits=["abc"],
    )
    assert per_pr_body == """## Backport Summary

Cherry-pick applied cleanly with no conflicts.

| Field | Value |
|---|---|
| Source PR | [#42](https://github.com/o/r/pull/42) |
| Source title | Fix \\| parser<br>handling |
| Target branch | `8.1` |
| Cherry-picked commits | 1 |
| Conflicts detected | no |
| Auto-resolved files | 0 |
| Unresolved files | 0 |

### Reviewer Checklist

- Compare this backport against the source PR before merge.

### Cherry-Picked Commits

- `abc`"""

    sweep_body = build_sweep_pr_body(
        BranchSweepResult(
            target_branch="8.1",
            candidates_found=1,
            results=[
                CandidateResult(
                    42,
                    "Fix | parser\nhandling",
                    "applied",
                    "clean | pick\nkept",
                )
            ],
        )
    )
    assert sweep_body == """# Backport sweep for 8.1

Automated cherry-picks from PRs marked "To be backported".

## Applied

| Source PR | Title | Detail |
|---|---|---|
| #42 | Fix \\| parser handling | clean \\| pick kept |

---
*Generated by valkey-ci-agent using Claude Code.*"""


def test_git_runner_profiles_preserve_subprocess_semantics(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    calls: list[tuple[list[str], dict[str, object]]] = []

    def fake_run(cmd: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        calls.append((cmd, kwargs))
        return subprocess.CompletedProcess(cmd, 0, stdout="ok", stderr="")

    monkeypatch.setattr(main.subprocess, "run", fake_run)
    assert main._run_git("/repo", "status") is None
    assert calls.pop(0) == (
        ["git", "status"],
        {
            "cwd": "/repo",
            "capture_output": True,
            "text": True,
            "env": None,
        },
    )

    monkeypatch.setattr(cherry_pick_module.subprocess, "run", fake_run)
    cherry_result = cherry_pick_module._run_git("/repo", "status", check=False)
    assert cherry_result.stdout == "ok"
    assert calls.pop(0) == (
        ["git", "status"],
        {
            "cwd": "/repo",
            "capture_output": True,
            "text": True,
            "errors": "replace",
            "check": False,
        },
    )

    sweep_result = sweep_apply._run_captured_git(
        "/repo",
        "status",
        check=False,
        run_process=fake_run,
    )
    assert sweep_result.stdout == "ok"
    assert calls.pop(0) == (
        ["git", "status"],
        {
            "cwd": "/repo",
            "capture_output": True,
            "text": True,
        },
    )


def test_git_runner_profiles_preserve_failure_handling(
    monkeypatch: pytest.MonkeyPatch,
    caplog: pytest.LogCaptureFixture,
) -> None:
    def fail(cmd: list[str], **_kwargs: object) -> subprocess.CompletedProcess[str]:
        return subprocess.CompletedProcess(
            ["completed-process-command"],
            7,
            stdout="stdout",
            stderr="stderr",
        )

    monkeypatch.setattr(cherry_pick_module.subprocess, "run", fail)
    with pytest.raises(subprocess.CalledProcessError) as cherry_error:
        cherry_pick_module._run_git("/repo", "status")
    assert cherry_error.value.cmd == ["git", "status"]
    assert cherry_error.value.output == "stdout"
    assert cherry_error.value.stderr == "stderr"

    monkeypatch.setattr(main.subprocess, "run", fail)
    with caplog.at_level(logging.ERROR, logger="scripts.backport.main"):
        with pytest.raises(subprocess.CalledProcessError) as pipeline_error:
            main._run_git("/repo", "status")
    assert pipeline_error.value.cmd == ["completed-process-command"]
    assert "git status failed (rc=7)" in caplog.text


def test_main_git_runner_uses_current_module_dependencies(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    def fail(cmd: list[str], **_kwargs: object) -> subprocess.CompletedProcess[str]:
        return subprocess.CompletedProcess(cmd, 7, stdout="stdout", stderr="stderr")

    replacement_logger = Mock(spec=logging.Logger)
    monkeypatch.setattr(main, "logger", replacement_logger)
    monkeypatch.setattr(main, "subprocess", SimpleNamespace(run=fail))

    with pytest.raises(subprocess.CalledProcessError):
        main._run_git("/repo", "status")

    replacement_logger.debug.assert_called_once_with(
        "Running: %s (cwd=%s)",
        "git status",
        "/repo",
    )
    replacement_logger.error.assert_called_once_with(
        "git %s failed (rc=%d)\nstdout: %s\nstderr: %s",
        "status",
        7,
        "stdout",
        "stderr",
    )


def test_sweep_default_runner_uses_the_pipeline_profile(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    calls: list[tuple[list[str], dict[str, object]]] = []

    def fake_run(cmd: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        calls.append((cmd, kwargs))
        return subprocess.CompletedProcess(cmd, 0, stdout="", stderr="")

    monkeypatch.setattr(git.subprocess, "run", fake_run)
    git_env = {"GIT_ASKPASS": "/tmp/askpass"}

    assert git.run_pipeline_git("/repo", "fetch", "origin", env=git_env) is None
    assert calls == [
        (
            ["git", "fetch", "origin"],
            {
                "cwd": "/repo",
                "capture_output": True,
                "text": True,
                "env": git_env,
            },
        )
    ]


def test_per_pr_clone_keeps_full_history_and_post_clone_sequence(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    calls: list[tuple[list[str], dict[str, object]]] = []

    def fake_run(cmd: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        calls.append((cmd, kwargs))
        return subprocess.CompletedProcess(cmd, 0, stdout="", stderr="")

    monkeypatch.setattr(main.subprocess, "run", fake_run)
    git_env = {"GIT_ASKPASS": "/tmp/askpass"}
    assert main._clone_repo(
        "owner/repo",
        "/checkout",
        "8.1",
        git_env=git_env,
    ) is git_env

    assert calls == [
        (
            [
                "git",
                "clone",
                "--no-single-branch",
                "--branch",
                "8.1",
                "https://github.com/owner/repo.git",
                ".",
            ],
            {
                "check": True,
                "capture_output": True,
                "text": True,
                "env": git_env,
                "cwd": "/checkout",
            },
        ),
        (
            ["git", "config", "user.name", BOT_NAME],
            {
                "cwd": "/checkout",
                "check": True,
                "capture_output": True,
                "text": True,
            },
        ),
        (
            ["git", "config", "user.email", BOT_EMAIL],
            {
                "cwd": "/checkout",
                "check": True,
                "capture_output": True,
                "text": True,
            },
        ),
        (
            ["git", "fetch", "--all"],
            {
                "cwd": "/checkout",
                "check": True,
                "capture_output": True,
                "text": True,
                "env": git_env,
            },
        ),
    ]


def test_mark_done_clone_keeps_shallow_profile_without_post_clone_steps(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    calls: list[tuple[list[str], dict[str, object]]] = []

    def fake_run(cmd: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        calls.append((cmd, kwargs))
        return subprocess.CompletedProcess(cmd, 0, stdout="", stderr="")

    monkeypatch.setattr(mark_done.subprocess, "run", fake_run)
    git_env = {"GIT_ASKPASS": "/tmp/askpass"}
    mark_done._shallow_clone("owner/repo", "8.1", "/checkout", git_env)

    assert calls == [
        (
            [
                "git",
                "clone",
                "--branch",
                "8.1",
                "--single-branch",
                f"--depth={mark_done._VERIFY_CLONE_DEPTH}",
                "https://github.com/owner/repo.git",
                "/checkout",
            ],
            {
                "check": True,
                "capture_output": True,
                "text": True,
                "env": git_env,
            },
        )
    ]


@pytest.mark.parametrize(
    ("materialize_in_retry", "expected_order"),
    [
        (False, ["get", "retry-return", "iterate"]),
        (True, ["get", "iterate", "retry-return"]),
    ],
)
def test_pr_lookup_preserves_materialization_timing(
    monkeypatch: pytest.MonkeyPatch,
    materialize_in_retry: bool,
    expected_order: list[str],
) -> None:
    events: list[str] = []
    pull = SimpleNamespace(
        head=SimpleNamespace(repo=SimpleNamespace(full_name="fork/repo")),
    )

    class Pulls:
        def __iter__(self):
            events.append("iterate")
            return iter([pull])

    class Repo:
        def get_pulls(self, *, state: str, head: str) -> Pulls:
            assert (state, head) == ("open", "fork:agent/backport/sweep/8.1")
            events.append("get")
            return Pulls()

    def retry(operation, *, retries: int, description: str):
        assert (retries, description) == (2, "list PRs")
        result = operation()
        events.append("retry-return")
        return result

    monkeypatch.setattr(pr_creator, "retry_github_call", retry)

    assert find_pull_by_head(
        Repo(),
        base_repo="upstream/repo",
        push_repo="fork/repo",
        branch_name="agent/backport/sweep/8.1",
        state="open",
        retries=2,
        retry_description="list PRs",
        materialize_in_retry=materialize_in_retry,
    ) is pull
    assert events == expected_order


def test_sweep_pr_lookup_preserves_its_retry_binding(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    events: list[str] = []
    pull = SimpleNamespace(
        head=SimpleNamespace(repo=SimpleNamespace(full_name="fork/repo")),
    )

    class Repo:
        def get_pulls(self, *, state: str, head: str) -> list[object]:
            assert (state, head) == ("open", "fork:agent/backport/sweep/8.1")
            return [pull]

    class GitHub:
        def get_repo(self, name: str) -> Repo:
            assert name == "upstream/repo"
            return Repo()

    def sweep_retry(operation, *, retries: int, description: str):
        events.append(f"{retries}:{description}")
        return operation()

    def wrong_retry(*_args: object, **_kwargs: object) -> None:
        pytest.fail("sweep lookup used pr_creator.retry_github_call")

    monkeypatch.setattr(sweep_prs, "retry_github_call", sweep_retry)
    monkeypatch.setattr(pr_creator, "retry_github_call", wrong_retry)

    assert sweep_prs.find_existing_pr(
        GitHub(),
        "upstream/repo",
        "fork/repo",
        "agent/backport/sweep/8.1",
    ) is pull
    assert events == ["2:get upstream/repo", "2:list PRs"]


def test_project_queries_preserve_path_specific_field_sets() -> None:
    discovery = " ".join(sweep._project_items_query("organization").split())
    status = " ".join(mark_done._project_query("organization").split())

    assert "number title url merged mergedAt" in discovery
    assert "repository { nameWithOwner }" in discovery
    assert "mergeCommit { oid }" in discovery
    assert "commits(first: 100)" in discovery
    assert "ProjectV2ItemFieldTextValue" in discovery
    assert "ProjectV2ItemFieldSingleSelectValue" in discovery
    assert "ProjectV2ItemFieldNumberValue" in discovery
    assert "ProjectV2ItemFieldIterationValue" in discovery
    assert "fields(first: 100)" not in discovery
    assert "ProjectV2SingleSelectField" not in discovery

    assert "fields(first: 100)" in status
    assert "ProjectV2SingleSelectField" in status
    assert "options { id name }" in status
    assert "repository { nameWithOwner }" in status
    assert "ProjectV2ItemFieldSingleSelectValue" in status
    assert "title url merged" not in status
    assert "mergeCommit" not in status
    assert "commits(first: 100)" not in status
    assert "ProjectV2ItemFieldTextValue" not in status
    assert "ProjectV2ItemFieldNumberValue" not in status
    assert "ProjectV2ItemFieldIterationValue" not in status


@pytest.mark.parametrize(
    ("query", "require_id"),
    [
        (sweep._project_items_query("organization"), False),
        (mark_done._project_query("organization"), True),
    ],
)
def test_shared_project_loader_preserves_pagination(
    query: str,
    require_id: bool,
) -> None:
    calls: list[dict[str, object]] = []
    responses = [
        {
            "organization": {
                "projectV2": {
                    "id": "PVT_1",
                    "fields": {"nodes": [{"id": "field"}]},
                    "items": {
                        "nodes": [{"id": "first"}],
                        "pageInfo": {
                            "hasNextPage": True,
                            "endCursor": "cursor-1",
                        },
                    },
                }
            }
        },
        {
            "organization": {
                "projectV2": {
                    "id": "PVT_1",
                    "fields": {"nodes": []},
                    "items": {
                        "nodes": [{"id": "second"}],
                        "pageInfo": {
                            "hasNextPage": False,
                            "endCursor": None,
                        },
                    },
                }
            }
        },
    ]

    class FakeClient:
        def execute(
            self,
            _query: str,
            variables: dict[str, object],
        ) -> dict[str, object]:
            calls.append(variables)
            return responses.pop(0)

    project = load_project_v2(
        FakeClient(),
        project_owner="valkey-io",
        project_number=14,
        project_owner_type="organization",
        query=query,
        require_id=require_id,
    )

    assert [item["id"] for item in project.items] == ["first", "second"]
    assert project.id == "PVT_1"
    assert project.fields == [{"id": "field"}]
    assert calls == [
        {"owner": "valkey-io", "number": 14, "cursor": None},
        {"owner": "valkey-io", "number": 14, "cursor": "cursor-1"},
    ]


@pytest.mark.parametrize("require_id", [False, True])
def test_shared_project_loader_preserves_missing_project_error(
    require_id: bool,
) -> None:
    class MissingProjectClient:
        def execute(
            self,
            _query: str,
            _variables: dict[str, object],
        ) -> dict[str, object]:
            return {"organization": {"projectV2": None}}

    with pytest.raises(RuntimeError, match=r"^Project valkey-io/14 not found$"):
        load_project_v2(
            MissingProjectClient(),
            project_owner="valkey-io",
            project_number=14,
            project_owner_type="organization",
            query="query",
            require_id=require_id,
        )


def test_shared_project_loader_preserves_missing_id_policy() -> None:
    class IdlessProjectClient:
        def execute(
            self,
            _query: str,
            _variables: dict[str, object],
        ) -> dict[str, object]:
            return {
                "organization": {
                    "projectV2": {
                        "items": {
                            "nodes": [{"id": "item"}],
                            "pageInfo": {"hasNextPage": False, "endCursor": None},
                        }
                    }
                }
            }

    project = load_project_v2(
        IdlessProjectClient(),
        project_owner="valkey-io",
        project_number=14,
        project_owner_type="organization",
        query="query",
        require_id=False,
    )
    assert project.id == ""
    assert project.items == [{"id": "item"}]

    with pytest.raises(RuntimeError, match=r"^Project valkey-io/14 has no id$"):
        load_project_v2(
            IdlessProjectClient(),
            project_owner="valkey-io",
            project_number=14,
            project_owner_type="organization",
            query="query",
            require_id=True,
        )


def test_jsonl_result_parsers_preserve_whitespace_and_event_strictness() -> None:
    stdout = '{"type":"result","result":"  final answer  "}'
    assert conflict_resolver._agent_result_text(stdout) == "final answer"
    assert sweep_validation.extract_agent_result_text(stdout) == "final answer"
    assert sweep_apply.extract_agent_result_text(
        SimpleNamespace(stdout=stdout)
    ) == "  final answer  "

    assert sweep_validation.extract_agent_result_text("[]") == ""
    with pytest.raises(AttributeError):
        conflict_resolver._agent_result_text("[]")
    with pytest.raises(AttributeError):
        sweep_apply.extract_agent_result_text(SimpleNamespace(stdout="[]"))


def test_validate_branch_preserves_per_pr_empty_selection_skip(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Per-PR profile: no selected commands -> success without running anything."""
    calls: list[tuple[tuple[object, ...], dict[str, object]]] = []

    def fake_run_build_commands(
        *args: object, **kwargs: object
    ) -> tuple[bool, str]:
        calls.append((args, kwargs))
        return False, "must not run"

    monkeypatch.setattr(
        "scripts.common.build_validator.run_build_commands",
        fake_run_build_commands,
    )

    assert validate_branch(
        "/repo",
        "origin/8.1",
        [],
        [ValidationRule(paths=("src/*.c",), commands=("./runtest",))],
        run_empty=False,
        pass_log_path=False,
        changed_paths_func=lambda _repo, _base: ("docs/readme.md",),
    ) == (True, "")
    assert calls == []


def test_validate_branch_preserves_per_pr_positional_call_shape(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Per-PR profile: selected commands run without a log_path keyword."""
    calls: list[tuple[tuple[object, ...], dict[str, object]]] = []

    def fake_run_build_commands(
        *args: object, **kwargs: object
    ) -> tuple[bool, str]:
        calls.append((args, kwargs))
        return False, "compile failed"

    monkeypatch.setattr(
        "scripts.common.build_validator.run_build_commands",
        fake_run_build_commands,
    )

    assert validate_branch(
        "/repo",
        "origin/8.1",
        ["make"],
        [ValidationRule(paths=("src/*.c",), commands=("./runtest", "make"))],
        run_empty=False,
        pass_log_path=False,
        changed_paths_func=lambda _repo, _base: ("src/server.c",),
    ) == (False, "compile failed")
    assert calls == [(("/repo", ["make", "./runtest"]), {})]


def test_validate_branch_preserves_sweep_empty_run_and_log_path() -> None:
    """Sweep profile: empty selection still runs, forwarding log_path."""
    calls: list[tuple[str, list[str], str | None]] = []

    def run_commands(
        repo_dir: str,
        commands: list[str],
        log_path: str | None = None,
    ) -> tuple[bool, str]:
        calls.append((repo_dir, commands, log_path))
        return True, ""

    assert validate_branch(
        "/repo",
        "origin/8.1",
        [],
        [],
        log_path="/tmp/validation.log",
        run_empty=True,
        pass_log_path=True,
        run_commands=run_commands,
        changed_paths_func=lambda _repo, _base: (),
    ) == (True, "")
    assert calls == [("/repo", [], "/tmp/validation.log")]
