"""Render fuzzer analysis results into GitHub issue title, body, and comment text.

The rendering is fuzzer-specific (mentions scenario/seed/Valkey SHA, lists
deterministic anomalies); the surrounding create-or-update machinery lives
in :mod:`scripts.common.issue_dedup`.
"""

from __future__ import annotations

from typing import Callable

from scripts.common.issue_dedup import IssueContent
from scripts.common.markdown import (
    bounded_body,
    bounded_comment,
    bounded_title,
    escape_text,
    inline_code,
    markdown_link,
    table_cell,
)
from scripts.fuzzer.models import FuzzerRunAnalysis

MARKER_NAMESPACE = "valkey-ci-agent:fuzzer-issue"


def render_for(analysis: FuzzerRunAnalysis) -> Callable[[str, int], IssueContent]:
    """Return the render callable expected by ``IssueDedupPublisher.upsert``."""
    def _render(marker: str, occurrences: int) -> IssueContent:
        return IssueContent(
            title=_build_title(analysis),
            body=_render_body(analysis, marker, occurrences=occurrences),
            comment=_render_comment(analysis, occurrences),
            labels=tuple(analysis.suggested_labels),
        )
    return _render


def _build_title(analysis: FuzzerRunAnalysis) -> str:
    if analysis.root_cause_category:
        label = analysis.root_cause_category.replace("-", " ").replace("_", " ").title()
        return bounded_title(f"[fuzzer-run] {label}")
    if analysis.anomalies:
        return bounded_title(f"[fuzzer-run] {analysis.anomalies[0].title}")
    # Set only by _build_incomplete_analysis, which produces no anomalies or
    # root_cause_category, so this is reached only when both checks above miss.
    if analysis.analyzer_incomplete:
        return bounded_title("[fuzzer-run] Analyzer could not complete")
    return bounded_title("[fuzzer-run] Anomalous behavior detected")


def _render_body(analysis: FuzzerRunAnalysis, marker: str, *, occurrences: int) -> str:
    lines = [
        marker,
        f"<!-- {MARKER_NAMESPACE}:occurrences:{occurrences} -->",
        "",
        "## Fuzzer Run Analysis",
        "",
        f"**Verdict**: {escape_text(analysis.triage_verdict, multiline=False)}",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Run | {markdown_link(str(analysis.run_id), analysis.run_url)} |",
        f"| Status | {inline_code(analysis.overall_status)} |",
        f"| Conclusion | {inline_code(analysis.conclusion)} |",
        f"| Scenario | {inline_code(analysis.scenario_id or 'unknown')} |",
        f"| Seed | {inline_code(analysis.seed or 'unknown')} |",
    ]
    if analysis.tested_valkey_sha:
        lines.append(f"| Valkey SHA | {inline_code(analysis.tested_valkey_sha)} |")
    lines.extend([
        "",
        "### Summary",
        "",
        escape_text(analysis.summary, max_bytes=16 * 1024),
    ])
    if analysis.anomalies:
        lines.extend(["", "### Findings", ""])
        for a in analysis.anomalies[:10]:
            lines.append(
                f"- **[{table_cell(a.severity)}]** "
                f"{escape_text(a.title, max_bytes=1024, multiline=False)}: "
                f"{escape_text(a.evidence, max_bytes=4096)}",
            )
    if analysis.reproduction_hint:
        lines.extend([
            "",
            f"**Reproduce**: {inline_code(analysis.reproduction_hint)}",
        ])
    lines.extend(["", "---", "*Generated by valkey-ci-agent*"])
    return bounded_body("\n".join(lines))


def _render_comment(analysis: FuzzerRunAnalysis, count: int) -> str:
    lines = [
        f"## Occurrence #{count}",
        "",
        f"Run {markdown_link(str(analysis.run_id), analysis.run_url)} | "
        f"{inline_code(analysis.overall_status)} | "
        f"{inline_code(analysis.triage_verdict)}",
        "",
        escape_text(analysis.summary, max_bytes=16 * 1024),
    ]
    if analysis.anomalies:
        lines.append("")
        for a in analysis.anomalies[:5]:
            lines.append(
                f"- **[{table_cell(a.severity)}]** "
                f"{escape_text(a.title, max_bytes=1024, multiline=False)}: "
                f"{escape_text(a.evidence, max_bytes=4096)}",
            )
    return bounded_comment("\n".join(lines))
