"""Markdown reporting for scheduled backport sweeps."""

from __future__ import annotations

from scripts.backport.sweep_models import (
    DETAIL_ALREADY_ON_SWEEP_BRANCH,
    BranchSweepResult,
    CandidateResult,
)


def result_is_on_backport_branch(result: CandidateResult) -> bool:
    return result.outcome in {"applied", "applied-validation-failed"} or (
        result.outcome == "skipped-existing"
        and result.detail == DETAIL_ALREADY_ON_SWEEP_BRANCH
    )


def repair_diagnosis_from_detail(detail: str) -> str:
    prefix = "Claude repair diagnosis:\n"
    if not detail.startswith(prefix):
        return ""
    body = detail[len(prefix):]
    return body.split("\n\nValidation output:\n", 1)[0].strip()


def validation_failure_detail(output: str) -> str:
    """Preserve AI diagnosis while keeping routine validation logs compact."""
    diagnosis = repair_diagnosis_from_detail(output)
    if not diagnosis:
        return compact_validation_output(output)
    marker = "\n\nValidation output:\n"
    validation_tail = output.split(marker, 1)[1] if marker in output else ""
    return (
        "Claude repair diagnosis:\n"
        f"{diagnosis[:1500]}\n\n"
        "Validation output:\n"
        f"{compact_validation_output(validation_tail)}"
    )


def compact_validation_output(output: str, *, limit: int = 500) -> str:
    text = output.strip()
    if len(text) <= limit:
        return text
    return text[-limit:]


def build_pr_body(
    result: BranchSweepResult,
    *,
    validation_failed: bool = False,
) -> str:
    lines = [
        f"# Backport sweep for {result.target_branch}",
        "",
        'Automated cherry-picks from PRs marked "To be backported".',
        "",
    ]
    if validation_failed:
        lines.extend([
            "## Validation failed",
            "",
            "This draft PR preserves the attempted backport branch so "
            "maintainers can inspect and fix the validation failure instead "
            "of losing the work in scheduled-run logs.",
            "",
        ])
        diagnoses = [
            diagnosis
            for r in result.results
            if (diagnosis := repair_diagnosis_from_detail(r.detail))
        ]
        if diagnoses:
            lines.extend([
                "### Claude repair diagnosis",
                "",
                "```text",
                diagnoses[0][:1500],
                "```",
                "",
            ])

    applied = [
        r for r in result.results
        if result_is_on_backport_branch(r)
        and r.outcome != "applied-validation-failed"
    ]
    validation_failed_applied = [
        r for r in result.results
        if r.outcome == "applied-validation-failed"
    ]
    failed = [
        r for r in result.results
        if r.outcome not in {
            "applied",
            "applied-validation-failed",
            "skipped-existing",
        }
    ]

    if applied:
        lines.extend(["## Applied", "", "| Source PR | Title | Detail |", "|---|---|---|"])
        for r in applied:
            lines.append(
                f"| #{r.source_pr_number} | {_esc(r.source_pr_title)} | {_esc(r.detail)} |",
            )
        lines.append("")

    if validation_failed_applied:
        lines.extend([
            "## Applied (validation failed)",
            "",
            "These candidates are present on the backport branch, but validation failed.",
            "",
            "| Source PR | Title | Validation output |",
            "|---|---|---|",
        ])
        for r in validation_failed_applied:
            lines.append(
                f"| #{r.source_pr_number} | {_esc(r.source_pr_title)} | "
                f"{_esc(r.detail)} |",
            )
        lines.append("")

    if failed:
        lines.extend([
            "## Needs attention",
            "",
            "These candidates could not be applied automatically and need a maintainer to follow up.",
            "",
            f"<details><summary>{len(failed)} candidate(s)</summary>",
            "",
            "| Source PR | Title | Outcome | Reason |",
            "|---|---|---|---|",
        ])
        for r in failed:
            lines.append(
                f"| #{r.source_pr_number} | {_esc(r.source_pr_title)} | "
                f"{r.outcome} | {_esc(r.detail)} |",
            )
        lines.extend(["", "</details>", ""])

    lines.extend(["---", "*Generated by valkey-ci-agent using Claude Code.*"])
    return "\n".join(lines)


def build_summary(results: list[BranchSweepResult]) -> str:
    lines = ["## Backport Sweep", ""]
    for r in results:
        retained = sum(1 for c in r.results if result_is_on_backport_branch(c))
        validation_failed = sum(
            1 for c in r.results
            if c.outcome == "applied-validation-failed"
        )
        suffix = f" -- [PR]({r.pr_url})" if r.pr_url else ""
        if r.error:
            suffix += f" -- error: {r.error}"
        status = f"{retained}/{r.candidates_found} retained"
        if validation_failed:
            status += f" ({validation_failed} validation failed)"
        lines.append(f"- `{r.target_branch}`: {status}" + suffix)
    return "\n".join(lines)


def _esc(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")
