"""Markdown reporting for scheduled backport sweeps."""

from __future__ import annotations

from scripts.backport.sweep_models import (
    DETAIL_ALREADY_ON_SWEEP_BRANCH,
    BranchSweepResult,
    CandidateResult,
)


def result_is_on_backport_branch(result: CandidateResult) -> bool:
    return result.outcome == "applied" or (
        result.outcome == "skipped-existing"
        and result.detail == DETAIL_ALREADY_ON_SWEEP_BRANCH
    )


def repair_diagnosis_from_detail(detail: str) -> str:
    prefix = "Claude repair diagnosis:\n"
    if not detail.startswith(prefix):
        return ""
    body = detail[len(prefix):]
    return body.split("\n\nValidation output:\n", 1)[0].strip()


def validation_failure_detail(output: str) -> str:
    """Preserve AI diagnosis while keeping routine validation logs compact."""
    diagnosis = repair_diagnosis_from_detail(output)
    if not diagnosis:
        return compact_validation_output(output)
    marker = "\n\nValidation output:\n"
    validation_tail = output.split(marker, 1)[1] if marker in output else ""
    return (
        "Claude repair diagnosis:\n"
        f"{diagnosis[:1500]}\n\n"
        "Validation output:\n"
        f"{compact_validation_output(validation_tail)}"
    )


def compact_validation_output(output: str, *, limit: int = 500) -> str:
    text = output.strip()
    if len(text) <= limit:
        return text
    return text[-limit:]


def build_pr_body(
    result: BranchSweepResult,
) -> str:
    lines = [
        f"# Backport sweep for {result.target_branch}",
        "",
        'Automated cherry-picks from PRs marked "To be backported".',
        "",
    ]

    applied = [r for r in result.results if result_is_on_backport_branch(r)]
    failed = [
        r for r in result.results
        if r.outcome not in {"applied", "skipped-existing"}
    ]

    if result.branch_notes:
        lines.extend(["## Branch updates", ""])
        for note in result.branch_notes:
            lines.append(f"- {_esc(note)}")
        lines.append("")

    if applied:
        lines.extend(["## Applied", "", "| Source PR | Title | Detail |", "|---|---|---|"])
        for r in applied:
            lines.append(
                f"| #{r.source_pr_number} | {_esc(r.source_pr_title)} | {_esc(r.detail)} |",
            )
        lines.append("")

    if failed:
        lines.extend([
            "## Needs attention",
            "",
            "These candidates could not be applied automatically and need a maintainer to follow up.",
            "",
            f"<details><summary>{len(failed)} candidate(s)</summary>",
            "",
            "| Source PR | Title | Outcome | Reason |",
            "|---|---|---|---|",
        ])
        for r in failed:
            lines.append(
                f"| #{r.source_pr_number} | {_esc(r.source_pr_title)} | "
                f"{r.outcome} | {_esc(r.detail)} |",
            )
        lines.extend(["", "</details>", ""])

    lines.extend(["---", "*Generated by valkey-ci-agent using Claude Code.*"])
    return "\n".join(lines)


def build_summary(results: list[BranchSweepResult]) -> str:
    lines = ["## Backport Sweep", ""]
    for r in results:
        applied = sum(1 for c in r.results if result_is_on_backport_branch(c))
        suffix = f" -- [PR]({r.pr_url})" if r.pr_url else ""
        if r.error:
            suffix += f" -- error: {r.error}"
        lines.append(
            f"- `{r.target_branch}`: {applied}/{r.candidates_found} applied" + suffix
        )
    return "\n".join(lines)


def _esc(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")
