"""Open or recover the pull request for a published issue-driven CI fix."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from scripts.ci_fix.models import FixOutcome, OutcomeKind
from scripts.ci_fix.rendering import markdown_generated_text, normalize_generated_text
from scripts.common.github_client import retry_github_call

_PR_MARKER = "valkey-ci-agent:ci-fix-issue"


@dataclass(frozen=True)
class IssueFixPullRequest:
    number: int
    url: str
    branch_name: str


def create_issue_fix_pull_request(
    gh: Any,
    *,
    repo_full_name: str,
    issue_number: int,
    issue_url: str,
    run_id: int,
    base_branch: str,
    branch_name: str,
    outcome: FixOutcome,
    verified: bool,
    verification_sha: str = "",
    close_issue: bool = True,
    retries: int = 2,
) -> IssueFixPullRequest:
    """Create a draft PR or recover an existing PR without changing its state."""
    repo = retry_github_call(
        lambda: gh.get_repo(repo_full_name),
        retries=retries,
        description=f"get repository {repo_full_name}",
    )
    owner = repo_full_name.split("/", 1)[0]
    existing = _find_open_pull(
        repo,
        owner=owner,
        base_branch=base_branch,
        branch_name=branch_name,
        retries=retries,
    )
    if existing is not None:
        return _publication(existing, branch_name)

    proposal = outcome.proposal
    check = proposal.failing_check if proposal and proposal.failing_check else "CI failure"
    check = normalize_generated_text(check, limit=160) or "CI failure"
    check = check.replace("@", "at ")
    title = _fit_title(f"Fix CI failure: {check}")
    body = _pull_request_body(
        issue_number=issue_number,
        issue_url=issue_url,
        run_id=run_id,
        repo_full_name=repo_full_name,
        outcome=outcome,
        verified=verified,
        verification_sha=verification_sha,
        close_issue=close_issue,
    )
    try:
        pull = retry_github_call(
            lambda: repo.create_pull(
                base=base_branch,
                head=branch_name,
                title=title,
                body=body,
                draft=True,
            ),
            retries=retries,
            description=f"create issue fix PR for #{issue_number}",
        )
    except Exception:
        # A transient response can be lost after GitHub has already created the
        # PR, and a concurrent invocation can win between lookup and create.
        # Re-query the exact head/base pair before reporting an orphan branch.
        recovered = _find_open_pull(
            repo,
            owner=owner,
            base_branch=base_branch,
            branch_name=branch_name,
            retries=retries,
        )
        if recovered is None:
            raise
        pull = recovered
    return _publication(pull, branch_name)


def _find_open_pull(
    repo: Any,
    *,
    owner: str,
    base_branch: str,
    branch_name: str,
    retries: int,
) -> Any | None:
    pulls = list(
        retry_github_call(
            lambda: repo.get_pulls(
                state="open",
                base=base_branch,
                head=f"{owner}:{branch_name}",
            ),
            retries=retries,
            description=f"find pull request for {branch_name}",
        )
    )
    return pulls[0] if pulls else None


def _pull_request_body(
    *,
    issue_number: int,
    issue_url: str,
    run_id: int,
    repo_full_name: str,
    outcome: FixOutcome,
    verified: bool,
    verification_sha: str,
    close_issue: bool,
) -> str:
    proposal = outcome.proposal
    root_cause = markdown_generated_text(
        proposal.root_cause if proposal else outcome.summary
    )
    review = markdown_generated_text(outcome.review.reasoning) if outcome.review else ""
    run_url = f"https://github.com/{repo_full_name}/actions/runs/{run_id}"
    verification = _verification_summary(
        outcome,
        verified=verified,
        verification_sha=verification_sha,
    )
    lines = [
        f"<!-- {_PR_MARKER} issue=\"{issue_number}\" run=\"{run_id}\" -->",
        "## Summary",
        "",
        root_cause,
        "",
        "## Evidence",
        "",
        f"- Source issue: [#{issue_number}]({issue_url})",
        f"- Failing run: [Actions run]({run_url})",
        f"- Verification: {verification}",
    ]
    if review:
        lines.append(f"- Skeptic review: {review}")
    issue_reference = "Fixes" if close_issue else "Refs"
    lines.extend(
        [
            "",
            f"{issue_reference} #{issue_number}",
            "",
            "_Generated by valkey-ci-agent. This pull request is draft and is never auto-merged._",
        ]
    )
    return "\n".join(lines)


def _verification_summary(
    outcome: FixOutcome,
    *,
    verified: bool,
    verification_sha: str,
) -> str:
    if verified:
        backend = markdown_generated_text(outcome.verify_backend or "local", limit=300)
        return f"Targeted verification passed using `{backend}`."
    if outcome.kind is OutcomeKind.PUSHED:
        revision = f" `{verification_sha[:12]}`" if verification_sha else ""
        return (
            f"Targeted verification passed at failing-run commit{revision}, but "
            "the default branch had advanced. This draft relies on pull request "
            "CI for authoritative validation of the published branch."
        )
    if outcome.verify_backend == "macos":
        return (
            "The unpatched macOS baseline did not establish a reproducible "
            "failure. The patch passed repeated macOS runs and skeptic review, "
            "but this draft relies on pull request CI for authoritative validation."
        )
    run_result = outcome.run_result
    if run_result is not None and run_result.ran and run_result.passed:
        return (
            "The agent did not establish a failing baseline. The patch passed "
            "repeated post-change runs and skeptic review, but this draft relies "
            "on pull request CI for authoritative validation."
        )
    return (
        "The patch passed skeptic review, but the agent environment could not "
        "produce a reliable post-change test verdict. This draft is unverified "
        "and relies on pull request CI for authoritative validation."
    )


def _fit_title(title: str) -> str:
    title = " ".join(title.split())
    return title if len(title) <= 200 else title[:197].rstrip() + "..."


def _publication(pull: Any, branch_name: str) -> IssueFixPullRequest:
    return IssueFixPullRequest(
        number=int(getattr(pull, "number", 0) or 0),
        url=str(getattr(pull, "html_url", "") or ""),
        branch_name=branch_name,
    )
